CREATE TABLE IF NOT EXISTS EMPLEADOS(
    ID_EMPLEADOS INT AUTO_INCREMENT NOT NULL,
    RUT VARCHAR(14) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    GENERO_EMPLEADO CHAR(1) NOT NULL,
    DIRECCION VARCHAR(50),
    TELEFONO VARCHAR(12),
    CONSTRAINT PK_EMPLEADOS_ID PRIMARY KEY(ID_EMPLEADOS),
    CONSTRAINT UQ_EMPLEADOS_RUT UNIQUE(RUT),
    CONSTRAINT CHK_GENERO_EMPLEADO CHECK (GENERO_EMPLEADO IN ('M', 'F'))
);

CREATE TABLE IF NOT EXISTS DATOS_LABORALES(
    ID_DATOS_LABORALES INT AUTO_INCREMENT NOT NULL,
    CARGO VARCHAR(30),
    FECHA_INGRESO VARCHAR(30),
    AREA VARCHAR(10),
    DEPARTAMENTO VARCHAR(10),
    ID_EMPLEADOS INT,
    CONSTRAINT PK_DATOS_LABORALES_ID PRIMARY KEY(ID_DATOS_LABORALES),
    CONSTRAINT FK_DATOS_LABORALES_ID_EMPLEADOS FOREIGN KEY (ID_EMPLEADOS) REFERENCES EMPLEADOS (ID_EMPLEADOS)
);

CREATE TABLE IF NOT EXISTS CONTACTO_EMERGENCIA(
    ID_CONTACTO_EMERGENCIA INT AUTO_INCREMENT NOT NULL,
    NOMBRE_CONTACTO VARCHAR(30),
    RELACION VARCHAR(10),
    TELEFONO_CONTACTO VARCHAR(12),
    ID_EMPLEADOS INT,
    CONSTRAINT PK_CONTACTO_EMERGENCIA_ID PRIMARY KEY(ID_CONTACTO_EMERGENCIA),
    CONSTRAINT FK_CONTACTO_EMERGENCIA_ID_EMPLEADOS FOREIGN KEY (ID_EMPLEADOS) REFERENCES EMPLEADOS (ID_EMPLEADOS)
);

CREATE TABLE IF NOT EXISTS CARGA_FAMILIAR(
    ID_CARGA_FAMILIAR INT AUTO_INCREMENT NOT NULL,
    NOMBRE_CARGA VARCHAR(30),
    PARENTESCO VARCHAR(10),
    GENERO_CARGA CHAR(1),
    RUT_CARGA VARCHAR(14),
    ID_EMPLEADOS INT,
    CONSTRAINT PK_CARGA_FAMILIAR_ID PRIMARY KEY(ID_CARGA_FAMILIAR),
    CONSTRAINT FK_CARGA_FAMILIAR_ID_EMPLEADOS FOREIGN KEY (ID_EMPLEADOS) REFERENCES EMPLEADOS (ID_EMPLEADOS),
    CONSTRAINT UQ_RUT_CARGA UNIQUE (RUT_CARGA)
);

CREATE TABLE IF NOT EXISTS USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT NOT NULL,
    RUT VARCHAR(14) NOT NULL,
    NOMBRE_USUARIO VARCHAR(50) NOT NULL,
    CONTRASENA VARCHAR(100) NOT NULL,
    CONSTRAINT PK_USUARIOS_ID PRIMARY KEY(ID_USUARIO),
    CONSTRAINT UQ_USUARIOS_RUT UNIQUE(RUT),
    CONSTRAINT FK_USUARIOS_RUT FOREIGN KEY (RUT) REFERENCES EMPLEADOS(RUT)
);


ALTER TABLE empleados ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE datos_laborales ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE contacto_emergencia ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE carga_familiar ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
